
export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const SET_IDENTITY = 'SET_IDENTITY'
export const CLEAR_IDENTITY = 'CLEAR_IDENTITY'

export const SET_SETTING = 'SET_SETTING'
export const INC_SETTING = 'INC_SETTING'

export const SET_ROUTE = 'SET_ROUTE'

export const RECEIVE_WORKSPACE = 'RECEIVE_WORKSPACE'
export const RECEIVE_WORKSPACE_LIST = 'RECEIVE_WORKSPACE_LIST'

export const RECEIVE_USER = 'RECEIVE_USER'
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST'
